#!/usr/bin/env python3
"""ros2-package-generator.py — ROS2 package generator."""

import os
import argparse
from pathlib import Path

SKIP = {'ament_cmake', 'ament_cmake_python', 'ament_lint_auto', 'ament_lint_common'}


def parse_deps(s):
    seen, out = set(), []
    for d in s.split(','):
        d = d.strip()
        if d and d not in seen:
            seen.add(d); out.append(d)
    return out


def class_name(pkg):
    return ''.join(w.capitalize() for w in pkg.split('_'))


def gen_cmake(pkg, deps):
    fp = '\n'.join('find_package({} REQUIRED)'.format(d) for d in deps if d not in SKIP)
    td = '\n'.join('  {}'.format(d) for d in deps if d not in SKIP)
    return (
        "cmake_minimum_required(VERSION 3.16)\n"
        "project({})\n\n"
        "if(CMAKE_VERSION VERSION_LESS \"3.16.0\")\n"
        "  cmake_policy(SET CMP0077 NEW)\n"
        "endif()\n\n"
        "if(NOT CMAKE_CXX_STANDARD)\n"
        "  set(CMAKE_CXX_STANDARD 17)\n"
        "  set(CMAKE_CXX_STANDARD_REQUIRED ON)\n"
        "endif()\n\n"
        "if(CMAKE_CXX_COMPILER_ID STREQUAL \"GNU\")\n"
        "  add_compile_options(-Wall -Wextra -Wpedantic -Wno-unused-parameter)\n"
        "endif()\n\n"
        "# dependencies\n"
        "{}\n\n"
        "include_directories(include)\n\n"
        "add_library(${{PROJECT_NAME}} SHARED\n"
        "  src/${{PROJECT_NAME}}_node.cpp\n)\n\n"
        "ament_target_dependencies(${{PROJECT_NAME}}\n"
        "{}\n)\n\n"
        "ament_export_dependencies(rclcpp)\n"
        "ament_export_include_directories(include)\n"
        "ament_export_libraries(${{PROJECT_NAME}})\n\n"
        "install(TARGETS ${{PROJECT_NAME}}\n"
        "  ARCHIVE DESTINATION lib\n"
        "  LIBRARY DESTINATION lib\n"
        "  RUNTIME DESTINATION lib)\n\n"
        "install(DIRECTORY launch config DESTINATION share/${{PROJECT_NAME}})\n\n"
        "if(BUILD_TESTING)\n"
        "  find_package(ament_lint_auto REQUIRED)\n"
        "  ament_lint_auto_find_test_cmake_files()\n"
        "endif()\n\n"
        "ament_package()\n"
    ).format(pkg, fp, td)


def gen_pkg_xml(pkg, deps, pkg_type):
    dep_lines = '\n'.join('  <depend>{}</depend>'.format(d) for d in deps if d not in SKIP)
    buildtool = '  <buildtool_depend>ament_cmake_python</buildtool_depend>\n' if pkg_type in ('python', 'mixed') else ''
    return (
        '<?xml version="1.0"?>\n'
        '<?xml-model href="http://download.ros.org/schema/package_format3.xsd"?>\n'
        '<package format="3">\n'
        '  <name>{}</name>\n'
        '  <version>0.1.0</version>\n'
        '  <description>TODO: 描述这个包的功能</description>\n'
        '  <maintainer email="dev@miuav.com">MIUAV Developer</maintainer>\n'
        '  <license>Apache-2.0</license>\n'
        '  <buildtool_depend>ament_cmake</buildtool_depend>\n'
        '{}{}'
        '  <test_depend>ament_lint_auto</test_depend>\n'
        '  <test_depend>ament_lint_common</test_depend>\n'
        '  <export><build_type>ament_cmake</build_type></export>\n'
        '</package>\n'
    ).format(pkg, buildtool, dep_lines)


def gen_lifecycle_node(pkg):
    cn = class_name(pkg)
    return (
        '// {}_node.cpp — LifecycleNode\n'
        '// generated by ros2-package-generator.py\n\n'
        '#include <rclcpp/rclcpp.hpp>\n'
        '#include <rclcpp_lifecycle/rclcpp_lifecycle.hpp>\n'
        '#include <lifecycle_msgs/msg/transition.hpp>\n'
        '#include <std_msgs/msg/string.hpp>\n\n'
        'class {}Node : public rclcpp_lifecycle::LifecycleNode {{\n'
        'public:\n'
        '  {}Node() : rclcpp_lifecycle::LifecycleNode("{}") {{\n'
        '    RCLCPP_INFO(get_logger(), "LifecycleNode 构造");\n'
        '  }}\n\n'
        '  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn\n'
        '  on_configure(const rclcpp::State&) override {{\n'
        '    RCLCPP_INFO(get_logger(), "[Lifecycle] Configuring...");\n'
        '    pub_ = this->create_publisher<std_msgs::msg::String>("/output", rclcpp::QoS(10).reliable());\n'
        '    RCLCPP_INFO(get_logger(), "[Lifecycle] Configured");\n'
        '    return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::SUCCESS;\n'
        '  }}\n\n'
        '  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn\n'
        '  on_activate(const rclcpp::State&) override {{\n'
        '    RCLCPP_INFO(get_logger(), "[Lifecycle] Activating...");\n'
        '    pub_->on_activate();\n'
        '    RCLCPP_INFO(get_logger(), "[Lifecycle] Activated");\n'
        '    return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::SUCCESS;\n'
        '  }}\n\n'
        '  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn\n'
        '  on_deactivate(const rclcpp::State&) override {{\n'
        '    RCLCPP_INFO(get_logger(), "[Lifecycle] Deactivating...");\n'
        '    pub_->on_deactivate();\n'
        '    return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::SUCCESS;\n'
        '  }}\n\n'
        '  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn\n'
        '  on_cleanup(const rclcpp::State&) override {{\n'
        '    RCLCPP_INFO(get_logger(), "[Lifecycle] Cleaning up...");\n'
        '    pub_.reset();\n'
        '    return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::SUCCESS;\n'
        '  }}\n\n'
        '  rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn\n'
        '  on_shutdown(const rclcpp::State&) override {{\n'
        '    RCLCPP_INFO(get_logger(), "[Lifecycle] Shutting down...");\n'
        '    pub_.reset();\n'
        '    return rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn::SUCCESS;\n'
        '  }}\n\n'
        'private:\n'
        '  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr pub_;\n'
        '}};\n\n'
        'int main(int argc, char* argv[]) {{\n'
        '  rclcpp::init(argc, argv);\n'
        '  auto node = std::make_shared<{}Node>();\n'
        '  rclcpp::executors::MultiThreadedExecutor executor;\n'
        '  executor.add_node(node->get_node_base_interface());\n'
        '  executor.spin();\n'
        '  rclcpp::shutdown();\n'
        '  return 0;\n'
        '}}\n'
    ).format(pkg, cn, cn, pkg, cn)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('pkg_name')
    ap.add_argument('pkg_type', nargs='?', default='cpp')
    ap.add_argument('deps', nargs='?', default='rclcpp,std_msgs')
    ap.add_argument('--node-type', default='lifecycle',
                    choices=['lifecycle', 'publisher', 'subscriber', 'service', 'timer'])
    args = ap.parse_args()

    pkg, deps, pkg_type = args.pkg_name, parse_deps(args.deps), args.pkg_type

    for d in [f'{pkg}/src', f'{pkg}/launch', f'{pkg}/config']:
        os.makedirs(d, exist_ok=True)

    Path(f'{pkg}/CMakeLists.txt').write_text(gen_cmake(pkg, deps))
    Path(f'{pkg}/package.xml').write_text(gen_pkg_xml(pkg, deps, pkg_type))

    if pkg_type in ('cpp', 'mixed') and args.node_type == 'lifecycle':
        Path(f'{pkg}/src/{pkg}_node.cpp').write_text(gen_lifecycle_node(pkg))

    launch = (
        '"""launch for {}"""\n'
        'from launch import LaunchDescription\n'
        'from launch_ros.actions import Node\n\n\n'
        'def generate_launch_description() -> LaunchDescription:\n'
        '    return LaunchDescription([\n'
        '        Node(package="{}", executable="{}_node",\n'
        '             name="{}", output="screen"),\n'
        '    ])\n'
    ).format(pkg, pkg, pkg, pkg)
    Path(f'{pkg}/launch/{pkg}.launch.py').write_text(launch)

    Path(f'{pkg}/config/params.yaml').write_text('/**:\n  ros__parameters:\n    node_name: "{}"\n'.format(pkg))
    Path(f'{pkg}/README.md').write_text('# {}\n\nROS2 package\n\nDependencies:\n'.format(pkg) + ''.join('- {}\n'.format(d) for d in deps))

    print('Generated: {}/'.format(pkg))
    print('Next steps:')
    print('  1. cd {}'.format(pkg))
    print('  2. rosdep install --from-paths . --ignore-src -r -y')
    print('  3. colcon build --packages-select {}'.format(pkg))


if __name__ == '__main__':
    main()
