<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"?>
<package format="3">
  <name>ros2_launch_params</name>
  <version>0.1.0</version>
  <description>ROS2 Launch 参数传递示例 — DeclareLaunchArgument/remapping/namespace</description>
  <maintainer email="dev@miuav.com">MIUAV Developer</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>ros2-lifecycle-controller</exec_depend>
  <exec_depend>rclcpp-minimal-publisher</exec_depend>
  <exec_depend>rclcpp-minimal-subscriber</exec_depend>

  <export><build_type>ament_python</build_type></export>
</package>
