#!/usr/bin/env bash
set -euo pipefail

SCRIPT_NAME="$(basename "$0")"
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET="all"

usage() {
  cat <<'EOF'
Initialize AI agent bootstrap files for this workspace.

Usage:
  ./init-agent.sh [--target all|copilot|cursor]

Options:
  --target  Generate files for specific toolchain.
            all      Generate both Copilot and Cursor files (default)
            copilot  Generate only VS Code Copilot related files
            cursor   Generate only Cursor related files
  -h, --help  Show this help message
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      if [[ $# -lt 2 ]]; then
        echo "[ERROR] --target requires a value" >&2
        exit 1
      fi
      TARGET="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "[ERROR] Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ "$TARGET" != "all" && "$TARGET" != "copilot" && "$TARGET" != "cursor" ]]; then
  echo "[ERROR] Invalid target: $TARGET (expected all|copilot|cursor)" >&2
  exit 1
fi

if [[ ! -d "$ROOT_DIR/agents" ]]; then
  echo "[ERROR] agents directory not found. Please run this script at repository root." >&2
  exit 1
fi

to_rel_path() {
  local abs_path="$1"
  abs_path="${abs_path#"$ROOT_DIR/"}"
  echo "$abs_path"
}

extract_frontmatter_value() {
  local key="$1"
  local file_path="$2"

  awk -v key="$key" '
    BEGIN { in_frontmatter = 0 }
    /^---[[:space:]]*$/ {
      if (in_frontmatter == 0) {
        in_frontmatter = 1
        next
      } else {
        exit
      }
    }
    in_frontmatter == 1 && $0 ~ ("^" key ":[[:space:]]*") {
      sub("^" key ":[[:space:]]*", "", $0)
      print $0
      exit
    }
  ' "$file_path" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//"
}

collect_md_files() {
  local src_dir="$1"
  if [[ -d "$src_dir" ]]; then
    find "$src_dir" -type f -name "*.md" | sort
  fi
}

collect_skill_files() {
  local src_dir="$1"
  if [[ -d "$src_dir" ]]; then
    find "$src_dir" -type f -name "SKILL.md" | sort
  fi
}

mkdir -p "$ROOT_DIR/agents/generated"

mapfile -t SKILL_FILES < <(collect_skill_files "$ROOT_DIR/agents/skills")
mapfile -t PRINCIPLE_FILES < <(collect_md_files "$ROOT_DIR/agents/documents")
mapfile -t PROMPT_FILES < <(collect_md_files "$ROOT_DIR/agents/prompts")
mapfile -t ROBOT_GUIDE_FILES < <(collect_md_files "$ROOT_DIR/agents/robots")
mapfile -t MEMORY_FILES < <(collect_md_files "$ROOT_DIR/agents/memory-bank")

if [[ "${#SKILL_FILES[@]}" -eq 0 ]]; then
  echo "[ERROR] No SKILL.md files found under agents/skills" >&2
  exit 1
fi

SKILL_INDEX_FILE="$ROOT_DIR/agents/generated/skill-index.md"
SKILL_ROUTING_FILE="$ROOT_DIR/agents/generated/skill-routing.md"
CONTEXT_INDEX_FILE="$ROOT_DIR/agents/generated/context-index.md"
BOOTSTRAP_FILE="$ROOT_DIR/agents/generated/agent-bootstrap.md"

generate_skill_index() {
  {
    echo "<!-- AUTO-GENERATED BY init-agent.sh. DO NOT EDIT DIRECTLY. -->"
    echo "# Skill Index"
    echo
    echo "Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo
    echo "Total skills: ${#SKILL_FILES[@]}"
    echo
    echo "| Skill Name | Path | Description |"
    echo "|---|---|---|"

    for file_path in "${SKILL_FILES[@]}"; do
      local rel_path
      local skill_name
      local skill_desc

      rel_path="$(to_rel_path "$file_path")"
      skill_name="$(extract_frontmatter_value "name" "$file_path")"
      skill_desc="$(extract_frontmatter_value "description" "$file_path")"

      if [[ -z "$skill_name" ]]; then
        skill_name="$(basename "$(dirname "$file_path")")"
      fi

      if [[ -z "$skill_desc" ]]; then
        skill_desc="N/A"
      fi

      skill_desc="${skill_desc//|/\\|}"
      echo "| ${skill_name} | ${rel_path} | ${skill_desc} |"
    done
  } > "$SKILL_INDEX_FILE"
}

generate_skill_routing() {
  local tmp_rows
  local tmp_collision

  tmp_rows="$(mktemp)"
  tmp_collision="$(mktemp)"

  declare -A skill_name_counts=()

  for file_path in "${SKILL_FILES[@]}"; do
    local rel_path
    local after_path
    local taxonomy_path
    local top_level
    local skill_name

    rel_path="$(to_rel_path "$file_path")"
    after_path="${rel_path#agents/skills/}"
    taxonomy_path="$(dirname "$after_path")"
    top_level="${after_path%%/*}"
    skill_name="$(extract_frontmatter_value "name" "$file_path")"

    if [[ -z "$skill_name" ]]; then
      skill_name="$(basename "$(dirname "$file_path")")"
    fi

    printf "%s\t| %s | %s | %s | %s |\n" \
      "$top_level" "$top_level" "$taxonomy_path" "$skill_name" "$rel_path" >> "$tmp_rows"

    ((skill_name_counts["$skill_name"]+=1))
  done

  {
    echo "<!-- AUTO-GENERATED BY init-agent.sh. DO NOT EDIT DIRECTLY. -->"
    echo "# Skill Routing"
    echo
    echo "Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo
    echo "Use this file for fast routing when many skills share similar names."
    echo "Prefer full taxonomy path in prompts to avoid ambiguity."
    echo
    echo "| Top Level | Taxonomy Path | Skill Name | Path |"
    echo "|---|---|---|---|"
    sort -t $'\t' -k1,1 -k2,2 "$tmp_rows" | cut -f2-
    echo
    echo "## Name Collisions"

    for skill_name in "${!skill_name_counts[@]}"; do
      if [[ "${skill_name_counts[$skill_name]}" -gt 1 ]]; then
        printf "%s\t%d\n" "$skill_name" "${skill_name_counts[$skill_name]}" >> "$tmp_collision"
      fi
    done

    if [[ -s "$tmp_collision" ]]; then
      while IFS=$'\t' read -r name count; do
        echo "- ${name} (${count})"
      done < <(sort -t $'\t' -k2,2nr -k1,1 "$tmp_collision")
    else
      echo "- none"
    fi
  } > "$SKILL_ROUTING_FILE"

  rm -f "$tmp_rows" "$tmp_collision"
}

generate_context_index() {
  local core_rule_files=(
    "$ROOT_DIR/README.md"
    "$ROOT_DIR/agents/skills/README.md"
    "$ROOT_DIR/i18n/zh-CN/AGENT_IMPORT_GUIDE.md"
    "$ROOT_DIR/i18n/en/AGENT_IMPORT_GUIDE.md"
  )

  local mcp_assets=(
    "$ROOT_DIR/.vscode/mcp.json"
    "$ROOT_DIR/.cursor/mcp.json"
  )

  {
    echo "<!-- AUTO-GENERATED BY init-agent.sh. DO NOT EDIT DIRECTLY. -->"
    echo "# Context Index"
    echo
    echo "Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo

    echo "## Core Rules"
    for file_path in "${core_rule_files[@]}"; do
      if [[ -f "$file_path" ]]; then
        echo "- $(to_rel_path "$file_path")"
      fi
    done
    echo

    echo "## Project Principles"
    if [[ "${#PRINCIPLE_FILES[@]}" -eq 0 ]]; then
      echo "- (none found)"
    else
      for file_path in "${PRINCIPLE_FILES[@]}"; do
        echo "- $(to_rel_path "$file_path")"
      done
    fi
    echo

    echo "## Prompt Templates"
    if [[ "${#PROMPT_FILES[@]}" -eq 0 ]]; then
      echo "- (none found)"
    else
      for file_path in "${PROMPT_FILES[@]}"; do
        echo "- $(to_rel_path "$file_path")"
      done
    fi
    echo

    echo "## Robot Guides"
    if [[ "${#ROBOT_GUIDE_FILES[@]}" -eq 0 ]]; then
      echo "- (none found)"
    else
      for file_path in "${ROBOT_GUIDE_FILES[@]}"; do
        echo "- $(to_rel_path "$file_path")"
      done
    fi
    echo

    echo "## Memory Bank"
    if [[ "${#MEMORY_FILES[@]}" -eq 0 ]]; then
      echo "- (none found)"
    else
      for file_path in "${MEMORY_FILES[@]}"; do
        echo "- $(to_rel_path "$file_path")"
      done
    fi
    echo

    echo "## Skill Index"
    echo "- $(to_rel_path "$SKILL_INDEX_FILE")"
    echo

    echo "## Skill Routing"
    echo "- $(to_rel_path "$SKILL_ROUTING_FILE")"
    echo

    echo "## MCP Assets"
    for file_path in "${mcp_assets[@]}"; do
      if [[ -f "$file_path" ]]; then
        echo "- $(to_rel_path "$file_path")"
      fi
    done
  } > "$CONTEXT_INDEX_FILE"
}

generate_bootstrap_file() {
  {
    echo "<!-- AUTO-GENERATED BY init-agent.sh. DO NOT EDIT DIRECTLY. -->"
    echo "# vibe-coding-ros2 Agent Bootstrap"
    echo
    echo "This file defines one-click project bootstrap context for Copilot and Cursor agents."
    echo
    echo "## Required Loading Order"
    echo "1. agents/generated/context-index.md"
    echo "2. agents/generated/skill-index.md"
    echo "3. agents/generated/skill-routing.md"
    echo "4. agents/skills/README.md"
    echo "5. i18n/zh-CN/AGENT_IMPORT_GUIDE.md"
    echo "6. i18n/en/AGENT_IMPORT_GUIDE.md"
    echo
    echo "## Task Routing Rules"
    echo "- First decide robot type or edge platform type from user request."
    echo "- Then decide functional domain (perception/localization/navigation/action/etc.)."
    echo "- Finally load the exact SKILL.md from agents/generated/skill-index.md."
    echo "- If skill names collide, resolve with full taxonomy path from agents/generated/skill-routing.md."
    echo "- If multiple skills are relevant, load all relevant SKILL.md files before coding."
    echo
    echo "## MCP Development Rules"
    echo "- Prefer MCP tools for external data retrieval and automation when available."
    echo "- Keep tokens in environment variables; never hardcode credentials in files."
    echo "- VS Code MCP config path: .vscode/mcp.json"
    echo "- Cursor MCP config path: .cursor/mcp.json"
    echo "- For GitHub MCP, use GITHUB_PERSONAL_ACCESS_TOKEN from environment."
    echo
    echo "## Regeneration"
    echo "Run ./init-agent.sh again whenever skills, prompts, principles, or MCP strategy changes."
  } > "$BOOTSTRAP_FILE"
}

generate_copilot_files() {
  mkdir -p "$ROOT_DIR/.github"

  cat > "$ROOT_DIR/.github/copilot-instructions.md" <<'EOF'
<!-- AUTO-GENERATED BY init-agent.sh. DO NOT EDIT DIRECTLY. -->
# Copilot Workspace Instructions

Always bootstrap this project with:
- agents/generated/agent-bootstrap.md
- agents/generated/context-index.md
- agents/generated/skill-index.md
- agents/generated/skill-routing.md

Execution rules:
- Route user requests by robot/platform type, then by function domain, then load exact SKILL.md.
- If skill names collide, resolve by full taxonomy path from skill-routing.md.
- Use the project principles and prompt templates listed in context-index.md.
- When MCP is needed, follow .vscode/mcp.json configuration and MCP development rules.
- Never hardcode secrets; always read from environment variables.
EOF

  cat > "$ROOT_DIR/AGENTS.md" <<'EOF'
<!-- AUTO-GENERATED BY init-agent.sh. DO NOT EDIT DIRECTLY. -->
# AGENTS

This repository uses auto-generated AI bootstrap context.

Start from:
1. agents/generated/agent-bootstrap.md
2. agents/generated/context-index.md
3. agents/generated/skill-index.md
4. agents/generated/skill-routing.md

If a request maps to a specific domain, load corresponding SKILL.md before implementation.
EOF

  mkdir -p "$ROOT_DIR/.vscode"
  cat > "$ROOT_DIR/.vscode/mcp.json" <<'EOF'
{
  "mcpServers": {
    "filesystem": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", "."]
    },
    "fetch": {
      "command": "uvx",
      "args": ["mcp-server-fetch"]
    },
    "github": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-github"],
      "env": {
        "GITHUB_PERSONAL_ACCESS_TOKEN": "${env:GITHUB_PERSONAL_ACCESS_TOKEN}"
      }
    }
  }
}
EOF
}

generate_cursor_files() {
  mkdir -p "$ROOT_DIR/.cursor/rules"

  cat > "$ROOT_DIR/.cursor/rules/vibe-coding-ros2.mdc" <<'EOF'
---
description: Always load vibe-coding-ros2 principles, MCP rules, and full skill index before coding.
globs:
  - "**/*"
alwaysApply: true
---

Always bootstrap this workspace with:
- agents/generated/agent-bootstrap.md
- agents/generated/context-index.md
- agents/generated/skill-index.md
- agents/generated/skill-routing.md

Routing and execution rules:
- Match request to robot/platform taxonomy first.
- Match functional domain second.
- Load exact SKILL.md entries from skill-index.md before implementation.
- Resolve duplicate skill names via full path in skill-routing.md.
- Follow MCP development rules from agent-bootstrap.md.
EOF

  cat > "$ROOT_DIR/.cursor/mcp.json" <<'EOF'
{
  "mcpServers": {
    "filesystem": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", "."]
    },
    "fetch": {
      "command": "uvx",
      "args": ["mcp-server-fetch"]
    },
    "github": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-github"],
      "env": {
        "GITHUB_PERSONAL_ACCESS_TOKEN": "${env:GITHUB_PERSONAL_ACCESS_TOKEN}"
      }
    }
  }
}
EOF
}

generate_skill_index
generate_skill_routing

case "$TARGET" in
  all)
    generate_copilot_files
    generate_cursor_files
    ;;
  copilot)
    generate_copilot_files
    ;;
  cursor)
    generate_cursor_files
    ;;
esac

generate_context_index
generate_bootstrap_file

chmod +x "$ROOT_DIR/init-agent.sh"

echo "[OK] AI bootstrap initialization completed."
echo "[INFO] Target: $TARGET"
echo "[INFO] Generated files:"
echo "  - $(to_rel_path "$SKILL_INDEX_FILE")"
echo "  - $(to_rel_path "$SKILL_ROUTING_FILE")"
echo "  - $(to_rel_path "$CONTEXT_INDEX_FILE")"
echo "  - $(to_rel_path "$BOOTSTRAP_FILE")"

if [[ "$TARGET" == "all" || "$TARGET" == "copilot" ]]; then
  echo "  - .github/copilot-instructions.md"
  echo "  - AGENTS.md"
  echo "  - .vscode/mcp.json"
fi

if [[ "$TARGET" == "all" || "$TARGET" == "cursor" ]]; then
  echo "  - .cursor/rules/vibe-coding-ros2.mdc"
  echo "  - .cursor/mcp.json"
fi

echo "[INFO] Skill count: ${#SKILL_FILES[@]}"
